apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hospital-backend-secret
  namespace: stage
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore

  target:
    name: hospital-backend-secret

  dataFrom:
    - extract:
        key: hospital-backend-stage