apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-backend
  namespace: dev
  labels:
    app: hospital-backend
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospital-backend
  template:
    metadata:
      labels:
        app: hospital-backend
        environment: dev
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: backend
          image: :6eb7750
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: PORT
              value: "8080"
            - name: APP_ENV
              value: "dev"
            - name: CORS_ORIGIN
              value: "http://hospital-frontend-rehaan-818986458477.s3-website.ap-south-1.amazonaws.com,http://localhost:5173"
          envFrom:
            - secretRef:
                name: hospital-backend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: hospital-backend
  namespace: dev
  labels:
    app: hospital-backend
    environment: dev
spec:
  type: ClusterIP
  selector:
    app: hospital-backend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
