apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-backend
  labels:
    app: hospital-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hospital-backend
  template:
    metadata:
      labels:
        app: hospital-backend
    spec:
      containers:
        - name: backend
          image: 818986458477.dkr.ecr.ap-south-1.amazonaws.com/hospital-backend:739f6f5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: CORS_ORIGIN
              value: "*"
          envFrom:
            - secretRef:
                name: hospital-backend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: hospital-backend
  labels:
    app: hospital-backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 0.0.0.0/0
  selector:
    app: hospital-backend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
