apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hospital-admin-eks
  region: ap-south-1
  version: "1.31"

managedNodeGroups:
  - name: ng-general
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 30
    privateNetworking: false

iam:
  withOIDC: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
